import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "products",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  modal,
  children,
}: Readonly<{
  modal: React.ReactNode,
  children: React.ReactNode
}>) {

  return (
    <div>
        {children}
        {modal}
    </div>
  );
}
